
services:
  php:
    build: .
    container_name: php
    volumes:    
      - ./src:/var/www/html
    depends_on:
      - mysql
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:8080"                    
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    build:          
      dockerfile: db.dockerfile
    image: mymysql:8.0
    container_name: mysql
    env_file: ./src/.env
    volumes:
      - mysql_data:/var/lib/mysql  
    ports:
      - "3306:3306"                

volumes:
  mysql_data:
