CREATE TABLE IF NOT EXISTS motor (
    id_motor INT AUTO_INCREMENT PRIMARY KEY,
    nama_motor VARCHAR(100) NOT NULL,
    merek VARCHAR(100) NOT NULL,
    tipe VARCHAR(100),
    harga DECIMAL(12,2),
    gambar VARCHAR(255), 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
